server:
  port: 8083

car:
  totalCount: 100

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:carmgr
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    health:
      group:
        custom:
          showComponents: always
          showDetails: always